// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZzWhlKzyJLVS2Pz11WeKLjJhqA4CGo3s',
    appId: '1:272245710825:web:d7e183c7a83e65c960f578',
    messagingSenderId: '272245710825',
    projectId: 'excercise-roadmap',
    authDomain: 'excercise-roadmap.firebaseapp.com',
    storageBucket: 'excercise-roadmap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG781ilqGuTpJJkXY2cmgpzlNg9zuOxpk',
    appId: '1:272245710825:android:0503644b02ee7dfb60f578',
    messagingSenderId: '272245710825',
    projectId: 'excercise-roadmap',
    storageBucket: 'excercise-roadmap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TlHbb7kqfMG7UsI7-xbHnxpuiBgtB9g',
    appId: '1:272245710825:ios:893cee0dfc08618960f578',
    messagingSenderId: '272245710825',
    projectId: 'excercise-roadmap',
    storageBucket: 'excercise-roadmap.firebasestorage.app',
    iosBundleId: 'com.example.exerciseRoadmapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4TlHbb7kqfMG7UsI7-xbHnxpuiBgtB9g',
    appId: '1:272245710825:ios:893cee0dfc08618960f578',
    messagingSenderId: '272245710825',
    projectId: 'excercise-roadmap',
    storageBucket: 'excercise-roadmap.firebasestorage.app',
    iosBundleId: 'com.example.exerciseRoadmapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZzWhlKzyJLVS2Pz11WeKLjJhqA4CGo3s',
    appId: '1:272245710825:web:e244952389cc0c5460f578',
    messagingSenderId: '272245710825',
    projectId: 'excercise-roadmap',
    authDomain: 'excercise-roadmap.firebaseapp.com',
    storageBucket: 'excercise-roadmap.firebasestorage.app',
  );
}
